import argparse
import os
import sys
from pathlib import Path

base = Path(__file__).resolve().parent
project_root = base.parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from utils.aes import AESUtils
from utils.ansi import success, error, info, warning, color
from utils.env import read_env

env = read_env(base.parent / ".env")


def main():
    parser = argparse.ArgumentParser(
        description="AES encrypt a text file."
    )

    parser.add_argument(
        "--input-file",
        type=Path,
        required=True,
        help="Path to the input .txt file"
    )

    parser.add_argument(
        "--output-file",
        type=Path,
        required=True,
        help="Path to the encrypted output file"
    )

    parser.add_argument(
        "--key",
        type=str,
        help="Override AES encryption key from .env"
    )

    parser.add_argument(
        "--iv",
        type=str,
        help="Override AES initialization vector from .env"
    )

    parser.add_argument(
        "--mode",
        type=str,
        choices=["cbc"],
        help="Override AES mode from .env"
    )

    args = parser.parse_args()

    # CLI takes precedence over shared .env
    key = args.key or env.get("AES_ENCRYPT_KEY")
    iv = args.iv or env.get("AES_INITIAL_VECTOR")
    mode = args.mode or env.get("DEFAULT_AES_MODE")

    if not key:
        parser.error(error("AES key not provided. Use --key or set AES_ENCRYPT_KEY in .env"))

    if not iv:
        parser.error(error("AES IV not provided. Use --iv or set AES_INITIAL_VECTOR in .env"))

    if not mode:
        parser.error(error("AES mode not provided. Use --mode or set DEFAULT_AES_MODE in .env"))

    if not args.input_file.exists():
        parser.error(error(f"Input file does not exist: {args.input_file}"))

    try:
        # Read the normalized text generated by the previous script
        plaintext = args.input_file.read_text(encoding="utf-8")

        # Initialize AES utility
        aes = AESUtils(
            key=key,
            iv=iv,
            mode=mode
        )

        # Encrypt
        encrypted = aes.encrypt(plaintext)

        # Write HEX ciphertext
        args.output_file.write_text(
            encrypted,
            encoding="utf-8"
        )

        src = color(str(args.input_file), fg="bright_blue")
        dst = color(str(args.output_file), fg="bright_green")
        print(success(f"Encrypted {src} -> {dst}"))

    except ValueError as e:
        parser.error(error(str(e)))

    except OSError as e:
        parser.error(error(f"File error: {e}"))


if __name__ == "__main__":
    main()
